#!/usr/bin/env node

const { ElvClient } = require("@eluvio/elv-client-js");
const UrlJoin = require("url-join");

const fabutil = require("./deps/fabutil.js");
const { setDebug, debugDir } = require("./deps/debug.js");

const TAGSTORE_BASE = process.env.TAGSTORE_URL || "https://ai.contentfabric.io/tagstore"

async function main() {
  let args = process.argv
  
  while (args.length) {
    let arg = args.shift()
    if (arg.endsWith("vv.js")) break
  }

  const client = await fabutil.makeFabricClient()
  client.alwaysAttemptStateChannelAuth()
  await client.loadCachedTokens("cache-tokens.json")

  while (args.length > 0) {
    try {
      let iq = args.shift()
      console.log(`iq::${iq} ---`)
      const libraryId = await client.ContentObjectLibraryId({objectId: iq});    
      await processIq(client, iq, libraryId)
    }
    catch (error) {
      console.error(error)
    }
  }
}

async function readTagstoreTrack(client, contentId, track, has_frame_info = false) {
  
  const scToken = await client.GenerateStateChannelToken({ objectId: contentId }).catch((err) => { console.error(contentId, tracks, err) })
  
  if (!scToken) return {}
    
  const params = new URLSearchParams({
    track: track,
    has_frame_info: has_frame_info,
    limit: 6000,
  })
  
  const response = await fetch(`${TAGSTORE_BASE}/${contentId}/tags?${params}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${scToken}`
    }
  })
  
  if (response.status !== 200) {
    throw new Error(`Error fetching tags for ${contentId} track ${track}: ${response.status} ${response.statusText} ${await response.text()}`)
  }
  
  const tsResp = await response.json()

  return tsResp.tags
}

async function processIq(client, objectId, libraryId) {
  const me = {
    client: client
  }
  const func = doStuff.bind(me)

  const defaultOfferings = Object.keys(
    (await client.ContentObjectMetadata({
      libraryId,
      objectId,
      metadataSubtree: "offerings",
      select: [
        "*/ready",
        "*/media_struct/duration_rat"
      ]
    }) || {})
  ).filter(key => key.includes("default"));

  const vvTags = await readTagstoreTrack(client, objectId, "vertical_video", true)
  const shotTags = await readTagstoreTrack(client, objectId, "shot_detection", false)

  const resp = await func(objectId, libraryId, defaultOfferings, shotTags, vvTags)

  console.log(`iq::${objectId} vertical.bin COMPLETE hash:${resp.hash}`)


}

// this function is designed to be lifted from the middle of EVIE's code that does this
// so it has some weirdnesses (like this.client is the client)

async function doStuff(objectId, libraryId, defaultOfferings, shotTags, verticalVideoTags) {

      // Sort both tag arrays by start_time and end_time to ensure chronological processing
      // (tagstore returns in order but not sure if that is guaranteed)
      shotTags = shotTags.sort((a, b) => {
        return ((a.start_time ?? 0) - (b.start_time ?? 0)) || ((a.end_time ?? 0) - (b.end_time ?? 0));
      });
      verticalVideoTags = verticalVideoTags.sort((a, b) => {
        return ((a.start_time ?? 0) - (b.start_time ?? 0)) || ((a.end_time ?? 0) - (b.end_time ?? 0));
      });
  
      console.info(`Found ${shotTags.length} shot tags and ${verticalVideoTags.length} vertical video tags`)

      // Every vertical video tag must correspond to a shot tag (matched by start_time). Shots shorter
      // than 4000ms are allowed to have no corresponding vertical video tag; longer shots are not.
      // Verify start_times line up, because end_time for vertical is generated by the model's length measurement
      // of the generated shot-part, end_time can wobble
      let vtIndex = 0;
      for(let i = 0; i < shotTags.length; i++) {
        const shot = shotTags[i];
        const vt = verticalVideoTags[vtIndex];

        if(vt && shot.start_time === vt.start_time) {
          if(Math.abs(vt.end_time - shot.end_time) > 500) {
            throw Error(
              `Difference between end_times at shot index ${i} is greater than 500ms: ` +
              `shot: ${shot.start_time} vertical: ${vt.start_time})`
            );
          }
          vtIndex++;
          continue;
        }

        const shotDuration = (shot.end_time ?? 0) - (shot.start_time ?? 0);
        if(shotDuration >= 4000) {
          throw Error(
            `Shot at index ${i} (start: ${shot.start_time}, end: ${shot.end_time}) has no corresponding ` +
            `vertical video tag and is not shorter than 4000ms (duration: ${shotDuration}ms)`
          );
        }
      }

      if(vtIndex !== verticalVideoTags.length) {
        const orphan = verticalVideoTags[vtIndex];
        throw Error(
          `Vertical video tag at start_time ${orphan.start_time} does not correspond to any shot tag`
        );
      }

      // Build xValues, filling in missing frames:
      //   - frames before the first shot get 0.5
      //   - frames in gaps between shots get the last xValue of the preceding shot
      const xValues = [];

      verticalVideoTags.forEach(tag => {
        const currentFrameIdx = tag.frame_info?.frame_idx ?? 0;
        const coords = tag.additional_info?.["x-coordinates"] || [];

        if(xValues.length < currentFrameIdx) {
          const lastXValue = xValues.length ? xValues.slice(-1)[0] : Math.round(0.5 * 10000);
          while(xValues.length < currentFrameIdx) {
            xValues.push(lastXValue);
          }
        } else if(xValues.length > currentFrameIdx) {
          if (currentFrameIdx - xValues.length > 4) {
            throw Error(
              `Overlap in vertical video tag frame indices more than 4 frames, should never be more than 1. Tag ID: ${tag.id}. ` +
              `Current frame_idx ${currentFrameIdx} is more than 4 before already-populated frame ${xValues.length}.`
            );
          }
          xValues.length = currentFrameIdx
        }

        coords.forEach(x => {
          xValues.push(Math.round(x * 10000));
        });
      });

      // 3. Pack into Buffer as 4-byte Little Endian integers
      const buffer = Buffer.alloc(xValues.length * 4);
      xValues.forEach((value, i) => {
        buffer.writeInt32LE(value, i * 4);
      });

      const editResponse = await this.client.EditContentObject({
        libraryId,
        objectId
      });

      await this.client.UploadFiles({
        libraryId,
        objectId,
        writeToken: editResponse.write_token,
        fileInfo: [
          {
            path: "vertical.bin",
            mime_type: "application/octet-stream",
            size: buffer.length,
            data: buffer,
          },
        ],
      });

      for(const offering of defaultOfferings) {
        await this.client.ReplaceMetadata({
          libraryId,
          objectId,
          writeToken: editResponse.write_token,
          metadataSubtree: UrlJoin("/offerings", offering, "verticalize", "data"),
          metadata: {
            "/": "./files/vertical.bin"
          }
        });
      }

      return await this.client.FinalizeContentObject({
        libraryId,
        objectId,
        writeToken: editResponse.write_token,
        commitMessage: "EVIE: Upload vertical video information file"
      });

}


async function mainCatch() {
    try {
        setDebug(process.env.DEBUG == "true")
        await main()
    } catch (err) {
        console.error("Error in main:", err)
        process.exit(1)
    }
}

if (require.main === module) {
    mainCatch()
}
else {
    module.exports = {
      processIq,
      downloadTagFiles,
      findyes
    }
}

  
