content:
  parts_url: http://192.168.90.218/config?self&qspace=main
  config_url: https://host-154-14-185-98.contentfabric.io/config?self&qspace=main
  live_media_url: https://host-76-74-29-5.contentfabric.io/config?self&qspace=main

tagstore:
  base_url: https://ai.contentfabric.io/tagstore
  
tag_runner:
  poll_interval: 5.0
  max_jobs: 5

tag_converter:
  name_mapping:
    asr: Speech to Text
    caption: Object Detection
    celeb: Celebrity Detection
    logo: Logo Detection
    music: Music Detection
    ocr: Optical Character Recognition
    shot: Shot Detection
    llava: LLAVA Caption
  interval: 10
  coalesce_tracks: 
    - asr
    - french_asr
  single_tag_tracks:
    - music_detection
  max_sentence_words: 250

system:
  resources: 
    cpu_juice: 100
    ollama: 3
  gpus: ["gpu", "disabled", "disabled", "disabled", "disabled"]

fetcher:
  author: tagger
  max_downloads: 4

tagger:
  media_dir: data/parts

jobstore:
  base_url: data/jobstore

container_registry:
  base_dir: data/containers
  cache_dir: data/cache

model_configs:
  scene_description:
    image: "localhost/qwenvl:latest"
    type: "video"
    description: Scene Description
    resources: {
      "gpu": 1
    }
    scope: 
      type: "tag-aligned"
      track: shot_detection
    track_outputs: ["scene_description"]
    track_dependencies: ["shot_detection"]
  llava:
    image: "localhost/llava:latest"
    type: "frame"
    description: Frame Description
    resources: {
      "ollama": 1
    }
    track_outputs: ["llava_caption"]
  asr:
    image: "localhost/asr:latest"
    type: "audio"
    description: Speech to Text
    resources: {
      "gpu": 1
    }
    track_outputs: ["speech_to_text", "auto_captions"]
  euro_asr:
    image: "localhost/multilingual:latest"
    type: "audio"
    description: Multilingual Speech to Text
    resources: {
      "gpu": 1
    }
    track_outputs: ["euro_asr", "auto_captions"]
  caption:
    image: "localhost/caption:latest"
    type: "frame"
    description: Object Identification
    resources: {
      "gpu": 1
    }
    track_outputs: ["object_detection"]
  shot:
    image: "localhost/shot:latest"
    type: "video"
    description: Shot Detection
    resources: {
      "gpu": 1
    }
    track_outputs: ["shot_detection"]
  celeb:
    image: "localhost/celeb:latest"
    type: "frame"
    description: Celebrity Identification
    resources: {
      "gpu": 1,
      "cpu_juice": 35
    }
    track_outputs: ["celebrity_detection"]
  ocr:
    image: "localhost/ocr:latest"
    type: "frame"
    description: OCR
    resources: {
      "gpu": 1
    }
    track_outputs: ["optical_character_recognition"]
  logo:
    image: "localhost/logo:latest"
    type: "frame"
    description: Logo Identification
    resources: {
      "gpu": 1
    }
    track_outputs: ["logo_detection"]
  vertical_video:
    image: "localhost/verticalvideo:latest"
    type: "video"
    description: Focus Identification
    resources: {
      "gpu": 1
    }
    track_outputs: ["vertical_video", "focus_detection"]
    track_dependencies: ["shot_detection"]
  chapters:
    image: "localhost/chapter:latest"
    type: "processor"
    description: Chapter Generation
    resources: {
      "ollama": 1
    }
    content_aligned: True
    track_outputs: ["chapter"]
    track_dependencies: ["auto_captions"]
  pose:
    image: "localhost/pose:latest"
    type: "video"
    description: Pose Detection
    resources: {
      "gpu": 1
    }
    track_dependencies: ["shot_detection"]
  speaker:
    image: "localhost/speaker:latest"
    type: "audio"
    description: Speaker Identification
    resources: {
      "gpu": 1
    }
    content_aligned: True
    track_dependencies: ["auto_captions"]
    track_outputs: ["speaker_detection", "transcription"]
  music:
    image: "localhost/music:latest"
    type: "audio"
    description: Music Identification
    resources: {
      "cpu_juice": 8
    }
    track_outputs: ["music_detection"]
  evidence:
      image: "localhost/evidence:latest"
      type: "processor"
      description: Evidence Generation
      resources: {
        "ollama": 1
      }
      content_aligned: True
      track_outputs: ["evidence_v2"]

# used to map track name to human friendly label for UI display
label_resolver:
  mapping:
    llava_caption: LLAVA Caption
    speech_to_text: Speech to Text
    euro_asr: Euro ASR
    qwen: Video Summary
    run: Running?
    hit: Hit?
    hit2s: (sm)Hit?
    celebrate: Celebration?
    delivery: Delivery?
    vertical_video: Vertical Video Information
    speaker_detection: Speaker Recognition

user_info_resolver:
  fabric_url: https://main.net955305.contentfabric.io
  user_info_url: https://ai.contentfabric.io/ml/token_info