openapi: 3.0.3
info:
  title: Eluvio Tagger API
  x-logo:
    url: /docs/logo.png
  version: 1.0.0
  description: |
    API for running ML inference on Fabric content objects
paths:
  /{qid}/tag:
    post:
      tags:
        - Operate tagging
      summary:
        Tag content
      parameters:
        - name: qid
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartJobsRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartTaggingResponse'
        '400':
          description: Bad Request
        '502':
          description: Bad Gateway

  /{qid}/status:
    get:
      tags:
        - Operate tagging
      summary:
        Check status
      parameters:
        - name: qid
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '404':
          description: No jobs found

  /{qid}/stop:
    post:
      tags:
        - Operate tagging
      summary:
        Stop tagging jobs by content
      parameters:
        - name: qid
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopTaggingResponse'

  /{qid}/stop/{model}:
    post:
      tags:
        - Operate tagging
      summary:
        Stop tagging jobs by model
      parameters:
        - name: qid
          in: path
          required: true
          schema:
            type: string
        - name: model
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopTaggingResponse'

components:
  schemas:
    StartJobsRequest:
      type: object
      properties:
        options:
          $ref: '#/components/schemas/TaggerOptions'
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/JobSpec'
      required:
        - jobs

    TaggerOptions:
      type: object
      properties:
        destination_qid:
          type: string
          default: ""
          description: content where tags should be written to
        replace:
          type: boolean
          default: false
          description:
            replace already existing tagstore tags. set to false to retag, set to true to enbable diff-based tagging.
        max_fetch_retries:
          type: integer
          default: 3
          description:
            if a fetch operation fails, we can retry this many times before the job is marked as failed.
        scope:
          type: object
          additionalProperties: true
          example:
            {"type": "video", "start_time": 100, "end_time": 200}
          description: Scope of tagging. Format should match one of the Scope schemas.

    JobSpec:
      type: object
      properties:
        model:
          type: string
          example: asr
        model_params:
          type: object
          additionalProperties: true
        overrides:
          $ref: '#/components/schemas/TaggerOptions'
      required:
        - model

    ScopeVideo:
      type: object
      properties:
        type:
          type: string
          enum: [video]
        start_time:
          type: integer
          default: 0
          description: start time to tag (in seconds)
        end_time:
          type: integer
          default: 10000000000000000
          example: 600
          description: end time to tag (in seconds)
        stream:
          type: string
          default: ""
      required:
        - type

    ScopeProcessor:
      type: object
      properties:
        type:
          type: string
          enum: [processor]
        start_time:
          type: integer
          default: 0
        end_time:
          type: integer
          default: 10000000000000000
          example: 3000
        chunk_size:
          type: integer
          default: 600
        stream:
          type: string
          default: "video"
      required:
        - type

    ScopeAssets:
      type: object
      properties:
        type:
          type: string
          enum: [assets]
        assets:
          type: array
          items:
            type: string
          description: list of asset paths to tag
          example: ["assets/hello1.jpg", "assets/hello2.jpg"]
      required:
        - type

    ScopeLivestream:
      type: object
      properties:
        type:
          type: string
          enum: [livestream]
        stream:
          type: string
          default: "video"
        segment_length:
          type: integer
          default: 4
          description: tagging interval size (in seconds)
        max_duration:
          type: integer
          nullable: true
          description: maximum amount of content from livestream to tag (in seconds)
      required:
        - type

    StartTaggingResponse:
      type: object
      properties:
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/StartStatus'
      required:
        - jobs

    StartStatus:
      type: object
      properties:
        job_id:
          type: string
          example: "1234"
        model:
          type: string
          example: "asr"
        stream:
          type: string
          example: "audio_1"
        started:
          type: boolean
          example: true
        message:
          type: string
          example: "successfully started"
        error:
          type: string
          nullable: true
          example: null
      required:
        - job_id
        - model
        - stream
        - started
        - message

    StatusResponse:
      type: object
      properties:
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/JobStatus'
      required:
        - jobs

    JobStatus:
      type: object
      properties:
        job_id:
          type: string
          example: "1234"
        status:
          type: string
          example: "Fetching Content"
        time_running:
          type: number
          example: 1234
        tagging_progress:
          type: string
          example: "120/305"
        missing_tags:
          type: array
          description: list of sources which have no tags
          example: ["assets/hello.jpg", "assets/hello2.jpg"]
          items:
            type: string
        failed:
          type: array
          description: list of sources which failed to process
          items:
            type: string
          example: ["assets/bad.jpg"]
        model:
          type: string
          example: "asr"
        stream:
          type: string
          example: "audio_1"
      required:
        - job_id
        - status
        - time_running
        - tagging_progress
        - missing_tags
        - failed
        - model
        - stream

    StopTaggingResponse:
      type: object
      properties:
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/StopStatus'
        message:
          type: string
      required:
        - jobs
        - message

    StopStatus:
      type: object
      properties:
        job_id:
          type: string
        message:
          type: string
      required:
        - job_id
        - message